# Generated by Django 3.2.18 on 2023-04-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_auto_20230310_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='time_sheet',
            name='type',
            field=models.CharField(default='Entrada', max_length=50),
        ),
        migrations.AddField(
            model_name='vacations',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='vacations',
            name='type',
            field=models.CharField(default='Férias', max_length=50),
        ),
    ]
